version: "3"

services:
  # Next.js Development Server
  nextjs:
    build:
      context: ./ui
      target: dev # Use the dev stage in the Dockerfile
    container_name: nextjs-server
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # For file watching in Docker
    volumes:
      - ./ui:/app # Mount local code for live reloading
      # - ./ui/node_modules:/app/node_modules # Use host's node_modules
    ports:
      - "3000:3000" # Port for Next.js development server
    networks:
      - scentmatch-network
    depends_on:
      - fastapi

  # FastAPI Development Server
  fastapi:
    build: ./server # Path to your FastAPI app
    container_name: fastapi-server
    environment:
      - DB_HOST=postgres-db-DEV
      - DB_PORT=5432
      - DB_NAME=scentmatch_dev_db
      - DB_USER=DEV_USER
      - DB_PASSWORD=abcd
      - REDIS_HOST=redis-DEV
      - REDIS_PORT=6379
    depends_on:
      - postgres-db-DEV
      - minio-blob
      - redis
    networks:
      - scentmatch-network
    expose:
      - "8001" # Port FastAPI will run on (internal)
    ports:
      - "8001:8001" # External port to access your app via HTTP
    volumes:
      - ./server:/app # Mount local code for live reloading
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload --log-level debug


  # PostgreSQL Database
  postgres-db-DEV:
    image: postgres:latest
    container_name: postgres-db-DEV
    environment:
      POSTGRES_USER: DEV_USER
      POSTGRES_PASSWORD: abcd
      POSTGRES_DB: scentmatch_dev_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/db_init:/docker-entrypoint-initdb.d/ # Mount the folder with init scripts
    networks:
      - scentmatch-network
    ports:
      - "5432:5432"

  # MinIO Blob Storage
  minio-blob:
    image: minio/minio:latest
    container_name: minio-blob
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: /docker-entrypoint-init.d/init.sh
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000" # MinIO Web UI
      - "9090:9090" # MinIO Console
    networks:
      - scentmatch-network
    volumes:
      - minio-data:/data # Persistent storage for MinIO
      - ./config/scripts:/docker-entrypoint-init.d/ # Mount the init script
      - ./storage/blob_storage:/blob_storage # Mount the local blob_storage folder
  redis:
    image: redis:latest
    container_name: redis-DEV
    networks:
      - scentmatch-network
    ports:
      - "6379:6379" # Redis default port
networks:
  scentmatch-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data:
