version: "3"

services:
  # FastAPI Test Server
  fastapi:
    build: ./server
    container_name: fastapi-server-test
    command: >
      sh -c "python /app/scripts/wait_for_postgres.py && pytest -s -vv"
    environment:
      - DATABASE_URL=postgres://scentmatch_user:scentmatch_password@postgres-db-test:5432/scentmatch_test_db
    depends_on:
      - postgres-db-test
      - minio-blob-test
    networks:
      - scentmatch-network
    ports:
      - "8002:8001"
    volumes:
      - ./server:/app  # Mount local code

  # PostgreSQL Test Database
  postgres-db-test:
    image: postgres:latest
    container_name: postgres-db-test
    environment:
      POSTGRES_USER: scentmatch_user
      POSTGRES_PASSWORD: scentmatch_password
      POSTGRES_DB: scentmatch_test_db
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
      - ./config/db_init:/docker-entrypoint-initdb.d/  # SQL init scripts
    networks:
      - scentmatch-network
    ports:
      - "5433:5432"

  # MinIO Test Storage
  minio-blob-test:
    image: minio/minio:latest
    container_name: minio-blob-test
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: /docker-entrypoint-init.d/init.sh
    command: server /data --console-address ":9090"
    ports:
      - "9001:9000"
    networks:
      - scentmatch-network
    volumes:
      - minio-data-test:/data
      - ./config/scripts:/docker-entrypoint-init.d/
      - ./storage/blob_storage:/blob_storage

networks:
  scentmatch-network:
    driver: bridge

volumes:
  postgres-data-test:
  minio-data-test:
