version: "3"

services:
  # FastAPI Test Server
  fastapi:
    build: ./server
    container_name: fastapi-server-test
    command: >
      sh -c "python /app/scripts/wait_for_postgres.py && pytest -s -vv"
    environment:
      - DB_HOST=postgres-db-TST
      - DB_PORT=5432
      - DB_NAME=scentmatch_tst_db
      - DB_USER=TST_USER
      - DB_PASSWORD=eAkYlkiNGbedEntiaNdoGRAnateanguLUBMiT
      - REDIS_HOST=redis-TST
      - REDIS_PORT=6379
    depends_on:
      - postgres-db-TST
      - minio-blob-test
    networks:
      - scentmatch-network
    ports:
      - "8002:8001"
    volumes:
      - ./server:/app  # Mount local code

  # PostgreSQL Test Database
  postgres-db-TST:
    image: postgres:latest
    container_name: postgres-db-TST
    environment:
      POSTGRES_USER: TST_USER
      POSTGRES_PASSWORD: eAkYlkiNGbedEntiaNdoGRAnateanguLUBMiT
      POSTGRES_DB: scentmatch_tst_db
      REDIS_HOST: redis-TST
      REDIS_PORT: 6379
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
      - ./config/db_init:/docker-entrypoint-initdb.d/  # SQL init scripts
    networks:
      - scentmatch-network
    ports:
      - "5433:5432"

  # MinIO Test Storage
  minio-blob-test:
    image: minio/minio:latest
    container_name: minio-blob-test
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: /docker-entrypoint-init.d/init.sh
    command: server /data --console-address ":9090"
    ports:
      - "9001:9000"
    networks:
      - scentmatch-network
    volumes:
      - minio-data-test:/data
      - ./config/scripts:/docker-entrypoint-init.d/
      - ./storage/blob_storage:/blob_storage
  
  redis-TST:
    image: redis:latest
    container_name: redis-TST
    ports:
      - "6379:6379"
    networks:
      - scentmatch-network

networks:
  scentmatch-network:
    driver: bridge

volumes:
  postgres-data-test:
  minio-data-test:
