x-nextjs-service: &nextjs-service
  build:
    context: ./ui
    target: prod
  environment:
    - NODE_ENV=production
  networks:
    - scentmatch-network

services:
  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - nextjs_1
      - nextjs_2
      - nextjs_3
    networks:
      - scentmatch-network

  nextjs_1:
    <<: *nextjs-service
    container_name: nextjs-server-1

  nextjs_2:
    <<: *nextjs-service
    container_name: nextjs-server-2

  nextjs_3:
    <<: *nextjs-service
    container_name: nextjs-server-3
    depends_on:
      - fastapi

  fastapi:
    build: ./server
    container_name: fastapi-server
    environment:
      - DATABASE_URL=postgres://user:password@postgres-db-PRD/scentmatch
      - DB_HOST=postgres-db-PRD
      - DB_PORT=5432
      - DB_NAME=scentmatch_db
      - DB_USER=scentmatch_user
      - DB_PASSWORD=scentmatch_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres-db-PRD
    networks:
      - scentmatch-network
    ports:
      - "8001:8001"
    volumes:
      - ./server:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001

  postgres-db-PRD:
    image: postgres:latest
    container_name: postgres-db-PRD
    environment:
      POSTGRES_USER: scentmatch_user
      POSTGRES_PASSWORD: scentmatch_password
      POSTGRES_DB: scentmatch_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/db_init:/docker-entrypoint-initdb.d/
    networks:
      - scentmatch-network
    ports:
      - "5432:5432"
    mem_limit: 300m

  minio-blob-PRD:
    image: minio/minio:latest
    container_name: minio-blob-PRD
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: /docker-entrypoint-init.d/init.sh
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    networks:
      - scentmatch-network
    volumes:
      - minio-data:/data
      - ./config/scripts:/docker-entrypoint-init.d/
      - ./storage/blob_storage:/blob_storage

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - scentmatch-network
    volumes:
      - redis-data:/data
    mem_limit: 300m

networks:
  scentmatch-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data:
  redis-data:
