services:
  fastapi:
    build: ./server
    container_name: fastapi-server-test
    command: >
      sh -c "python /app/scripts/wait_for_postgres.py && pytest -s -vv"
    env_file:
      - ./config/env/.env.test
    depends_on:
      - postgres-db-TST
    networks:
      - scentmatch-network
    ports:
      - "8002:8001"
    volumes:
      - ./server:/app

  postgres-db-TST:
    image: postgres:latest
    container_name: postgres-db-TST
    env_file:
      - ./config/env/.env.test
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
      - ./config/db_init:/docker-entrypoint-initdb.d/
    networks:
      - scentmatch-network
    ports:
      - "5433:5432"

  redis-TST:
    image: redis:latest
    container_name: redis-TST
    ports:
      - "6379:6379"
    networks:
      - scentmatch-network

networks:
  scentmatch-network:
    driver: bridge

volumes:
  postgres-data-test:
  minio-blob-TST:
  minio-data-TST:
