version: "3"

services:
  # Next.js Development Server
  nextjs:
    build:
      context: ./ui
      target: dev # Use the dev stage in the Dockerfile
    container_name: nextjs-server
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # For file watching in Docker
    volumes:
      - ./ui:/app # Mount local code for live reloading
      # - ./ui/node_modules:/app/node_modules # Use host's node_modules
    ports:
      - "3000:3000" # Port for Next.js development server
    networks:
      - scentmatch-network
    depends_on:
      - fastapi

  # FastAPI Development Server
  fastapi:
    build: ./server # Path to your FastAPI app
    container_name: fastapi-server
    environment:
      - DATABASE_URL=postgres://user:password@postgres-db/scentmatch
    depends_on:
      - postgres-db
    networks:
      - scentmatch-network
    expose:
      - "8001" # Port FastAPI will run on (internal)
    ports:
      - "8001:8001" # External port to access your app via HTTP
    volumes:
      - ./server:/app # Mount local code for live reloading
      - /app/venv # Prevents overwriting venv in container

  # PostgreSQL Database
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: scentmatch_user
      POSTGRES_PASSWORD: scentmatch_password
      POSTGRES_DB: scentmatch_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d/ # Mount the folder with init scripts
    networks:
      - scentmatch-network
    ports:
      - "5432:5432"

  # MinIO Blob Storage
  minio-blob:
    image: minio/minio:latest
    container_name: minio-blob
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: /scripts/entrypoint.sh
    ports:
      - "9000:9000" # MinIO Web UI
      - "9090:9090" # MinIO Console
    networks:
      - scentmatch-network
    volumes:
      - minio-data:/data # Persistent storage for MinIO
      - ./scripts/entrypoint.sh:/scripts/entrypoint.sh # Mount the entrypoint script
      - ./scripts/init.sh:/scripts/init.sh # Mount the init script
      - ./blob_storage:/blob_storage # Mount the local blob_storage folder

networks:
  scentmatch-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data:
